name: 'Frontend Deployment'
on:
  # Manual trigger
  workflow_dispatch:

  # Automatic trigger on pull_request events
  pull_request:
    branches:
      - main

jobs:
  # linting job that fails if the code contain error
  # ==========================================
  # JOB 1 : LINTING 
  # ==========================================
  linting:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code source du dépôt
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: latest
      
      # 3. Installer les dépendances du projet (y compris ESLint)
      - name: Install dependencies
        run: npm ci

      # 4. linter executuion that return exit 1 if there is an error
      - name: Run ESLint Check
        run: npm run lint

  # ==========================================
  # JOB 2 : TESTS 
  # ==========================================

  # parallel test job that fails if test suit doesn't pass 
  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    # optionnel : "needs: lint" force les tests à attendre que le linting soit réussi

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Exécution de la suite de tests
      - name: Run Test Suite
        run: npm test -- --watchAll=false
        env:
          CI: true

  # ==========================================
  # JOB 3 : BUILD DOCKER & PUSH TO ECR
  # ==========================================
  build-and-push:
    name: Build & Push to Amazon ECR
    runs-on: ubuntu-latest
    needs: [lint, tests] # On ne build l'image QUE si les tests passent !
    
    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Se connecter à AWS (Utilise les Secrets de votre dépôt GitHub)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Authentifier Docker auprès de votre registre ECR privé
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Construire l'image et la pousser (C'est le bloc que nous avons vu ensemble)
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true # 'true' car on veut l'envoyer sur AWS maintenant
          # Récupère l'URL ECR générée dynamiquement à l'étape précédente + le nom de votre repo
          tags: ${{ steps.login-ecr.outputs.registry }}/mp-frontend:latest
          build-args: |
            REACT_APP_MOVIE_API_URL=http://localhost:5000

      

      
